const express = require('express')
const app = express()
const cors = require('cors')
require('./connection.jsx')
const User = require('./UserData.jsx')
const nodemailer = require('nodemailer')


app.use(cors())
// app.get('/', (req, res) => {
//     res.send('Hello World!')
// })
// app.use(express.json)
app.use(express.urlencoded({extended:true}))



// this email is used using nodemailer



app.post("/submit",(req,res)=>{
 
    const {name,email,phone,message} = req.body;
    function sendMail(){

        let transporter = nodemailer.createTransport({
            service: 'gmail',
            auth:{
                user:'enter your email',
                pass:'password generated by google auth',
            }
    })
    
    const mailOptions = {
        from:'write your email and authenticate it first from google',
        to:email,
        subject:"SS Construction",
        text:"Thank you for contacting us. We will get back to you soon."
    
    }
    transporter.sendMail(mailOptions,(err,info)=>{
        if(err){
            console.log(err)
        }
        else{
            console.log("email sent")
        }
    })
    }
User.find({email:email}).then(
    (userFound)=>{
    // if(userFound){
    //     res.send("User already exists")
    // }

    const data =  User.create({
        name,
        email,
        phone,
        message
    }).then(()=>{
        sendMail()
        // res.status(200).json({message:"User created"})
        // alert("User created")
        // res.redirect("/http://127.0.0.1:5500/theme/contact.html")
    }).catch((err)=>{
        // res.status(500).json({message:"User not created"})

    })
    

    }
)
    




})



// app.use(express.static("theme"))


// app.get('/',(req,res)=>{
//     res.sendFile(__dirname+"/theme/contact.html")
// })



app.listen(3000, () => {
    console.log('Example app listening on port 3000!')
}
)


